pipeline {
    agent any
    tools {
        jdk 'JDK'
        maven 'mvn'
        git 'Default'
    }
    stages {
        stage('--- Testing Java Sources ---') {
            steps {
                sh 'mvn clean'
                sh 'mvn test'
            }
        }
    }
}
